spring:
 application:
  name: Config-application


eureka:
 instance:
  prefer-ip-address: true
 client:
  register-with-eureka: true
  fetch-registry: true
  healthcheck:
   enabled: true
  service-url:
   defaultZone: http://localhost:8761/eureka/
